### ISSUE TITLE
information about semantic scuttle theme modification

### ISSUE THREAD

**Issue by xavierle** [rlehnhof/flat#1]
this is not a true issue concerning YOUR semantic scuttle theme but a general question concerning the semantic scutte theming possibilities.

actually on the main repository issues and wiki are unavailable

actually the sidebar is composed of the following blocks for logged in users
search
tag actions
linked tags
related tags

and for logged out users : 
search
linked tags 
related tags

i would like this order to be

searc
related tags
linked tags
tag actions

did you find a way to do this ?

**Comment by rlehnhof** [comment]
Good question. The following loop from _sidebar.tpl.php_ seems to import the different block files (linked tags, related tags etc.), but I don't understand how the files are being selected in the first place:

if (isset($sidebar_blocks) && count($sidebar_blocks)) {
    $size = count($sidebar_blocks);
    for ($i = 0; $i < $size; $i++) {
        $this->includeTemplate('sidebar.block.'. $sidebar_blocks[$i]);
    }
}

Maybe someone else can explain?

**Comment by xavierle** [comment]
actually

I also stand in front of that loop with the same question

This is sad that main contributor to semantic scuttle have not activates
the issues and wiki functions of its own repository.

Do not know how to contact him directlt for this

**Comment by cweiske** [comment]
@xavierle: The repository description says:

> Report bugs on sourceforge. http://semanticscuttle.sourceforge.net/
