### ISSUE TITLE
Interface broken in new Opera

### ISSUE THREAD

**Issue by larsborn** [rlehnhof/flat#2]
as I told you personally: the headlines in the overview are cliped.

**Comment by rlehnhof** [comment]
I remember seeing the mistake at your place yesterday, but I cannot reproduce it. Tried Opera 12, 25 and 26. Are you maybe using Opera beta 27 or Opera developer 28?

**Comment by larsborn** [comment]
Sorry. Should have added the version in the first place:

Version: 26.0.1656.60 - Opera is up to date
Update stream: Stable
System: Windows 8.1 64-bit (WoW64)

**Comment by larsborn** [comment]
here a screenshot, to clearify: ![clipboard01](https://cloud.githubusercontent.com/assets/1826897/6097321/123d4566-afba-11e4-8e39-879a88fe5aa3.jpg)

**Comment by larsborn** [comment]
since I installed your theme, you seemed to have made some fixes. I updated it and everything is looking good again. 

Sorry for any inconveniences. I guess, you can close this issue now ;-).

**Comment by rlehnhof** [comment]
I've been looking into this every now and then, assuming it was bad markup. Glad it's been resolved! ;)
